# Generated by Django 3.2.3 on 2021-05-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='dayi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='group_user',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='schedules',
            name='schedule',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='dayi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='schedule',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='id_tg',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='updown',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='updown',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='groupus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
